version: '3'
services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: npm run start:dev
  postgres:
    image: postgres:16.2
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
    external: true
env_file:
  - .env