version: '3'
services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src
      - ./node_modules:/app/node_modules
    command: npm run start:dev
    env_file:
      - .env
  postgres:
    image: postgres:16.2
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  postgres-data:
